/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'venka' at '8/12/16 11:23 PM' with Gradle 2.14
 *
 * @author venka, @date 8/12/16 11:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
